# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(357, 273)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 331, 31))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 60, 241, 201))
        self.widget.setObjectName("widget")
        self.numb_buttons = QtWidgets.QGridLayout(self.widget)
        self.numb_buttons.setContentsMargins(0, 0, 0, 0)
        self.numb_buttons.setObjectName("numb_buttons")
        self.push_Button_1 = QtWidgets.QPushButton(self.widget)
        self.push_Button_1.setObjectName("push_Button_1")
        self.numb_buttons.addWidget(self.push_Button_1, 0, 0, 1, 1)
        self.push_Button_2 = QtWidgets.QPushButton(self.widget)
        self.push_Button_2.setObjectName("push_Button_2")
        self.numb_buttons.addWidget(self.push_Button_2, 0, 1, 1, 1)
        self.push_Button_qw = QtWidgets.QPushButton(self.widget)
        self.push_Button_qw.setObjectName("push_Button_qw")
        self.numb_buttons.addWidget(self.push_Button_qw, 3, 0, 1, 1)
        self.push_Button_8 = QtWidgets.QPushButton(self.widget)
        self.push_Button_8.setObjectName("push_Button_8")
        self.numb_buttons.addWidget(self.push_Button_8, 2, 1, 1, 1)
        self.push_Button_0 = QtWidgets.QPushButton(self.widget)
        self.push_Button_0.setObjectName("push_Button_0")
        self.numb_buttons.addWidget(self.push_Button_0, 3, 1, 1, 1)
        self.push_Button_5 = QtWidgets.QPushButton(self.widget)
        self.push_Button_5.setObjectName("push_Button_5")
        self.numb_buttons.addWidget(self.push_Button_5, 1, 1, 1, 1)
        self.push_Button_3 = QtWidgets.QPushButton(self.widget)
        self.push_Button_3.setObjectName("push_Button_3")
        self.numb_buttons.addWidget(self.push_Button_3, 0, 3, 1, 1)
        self.push_Button_7 = QtWidgets.QPushButton(self.widget)
        self.push_Button_7.setObjectName("push_Button_7")
        self.numb_buttons.addWidget(self.push_Button_7, 2, 0, 1, 1)
        self.push_Button_4 = QtWidgets.QPushButton(self.widget)
        self.push_Button_4.setObjectName("push_Button_4")
        self.numb_buttons.addWidget(self.push_Button_4, 1, 0, 1, 1)
        self.push_Button_6 = QtWidgets.QPushButton(self.widget)
        self.push_Button_6.setObjectName("push_Button_6")
        self.numb_buttons.addWidget(self.push_Button_6, 1, 3, 1, 1)
        self.push_Button_9 = QtWidgets.QPushButton(self.widget)
        self.push_Button_9.setObjectName("push_Button_9")
        self.numb_buttons.addWidget(self.push_Button_9, 2, 3, 1, 1)
        self.push_Button_neg = QtWidgets.QPushButton(self.widget)
        self.push_Button_neg.setObjectName("push_Button_neg")
        self.numb_buttons.addWidget(self.push_Button_neg, 3, 3, 1, 1)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(260, 60, 81, 201))
        self.widget1.setObjectName("widget1")
        self.operation_buttons = QtWidgets.QVBoxLayout(self.widget1)
        self.operation_buttons.setContentsMargins(0, 0, 0, 0)
        self.operation_buttons.setObjectName("operation_buttons")
        self.push_plus_Button = QtWidgets.QPushButton(self.widget1)
        self.push_plus_Button.setObjectName("push_plus_Button")
        self.operation_buttons.addWidget(self.push_plus_Button)
        self.push_min_Button = QtWidgets.QPushButton(self.widget1)
        self.push_min_Button.setObjectName("push_min_Button")
        self.operation_buttons.addWidget(self.push_min_Button)
        self.push_mult_Button = QtWidgets.QPushButton(self.widget1)
        self.push_mult_Button.setObjectName("push_mult_Button")
        self.operation_buttons.addWidget(self.push_mult_Button)
        self.push_div_Button = QtWidgets.QPushButton(self.widget1)
        self.push_div_Button.setObjectName("push_div_Button")
        self.operation_buttons.addWidget(self.push_div_Button)
        self.push_exp_Button = QtWidgets.QPushButton(self.widget1)
        self.push_exp_Button.setObjectName("push_exp_Button")
        self.operation_buttons.addWidget(self.push_exp_Button)
        self.push_square_Button = QtWidgets.QPushButton(self.widget1)
        self.push_square_Button.setObjectName("push_square_Button")
        self.operation_buttons.addWidget(self.push_square_Button)
        self.push_get_resolt = QtWidgets.QPushButton(self.widget1)
        self.push_get_resolt.setObjectName("push_get_resolt")
        self.operation_buttons.addWidget(self.push_get_resolt)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.push_Button_5, self.push_Button_7)
        Form.setTabOrder(self.push_Button_7, self.push_Button_6)
        Form.setTabOrder(self.push_Button_6, self.push_Button_1)
        Form.setTabOrder(self.push_Button_1, self.push_Button_9)
        Form.setTabOrder(self.push_Button_9, self.push_Button_4)
        Form.setTabOrder(self.push_Button_4, self.push_Button_3)
        Form.setTabOrder(self.push_Button_3, self.push_Button_2)
        Form.setTabOrder(self.push_Button_2, self.push_Button_8)
        Form.setTabOrder(self.push_Button_8, self.push_Button_qw)
        Form.setTabOrder(self.push_Button_qw, self.push_Button_neg)
        Form.setTabOrder(self.push_Button_neg, self.push_plus_Button)
        Form.setTabOrder(self.push_plus_Button, self.push_min_Button)
        Form.setTabOrder(self.push_min_Button, self.push_mult_Button)
        Form.setTabOrder(self.push_mult_Button, self.push_div_Button)
        Form.setTabOrder(self.push_div_Button, self.push_exp_Button)
        Form.setTabOrder(self.push_exp_Button, self.push_square_Button)
        Form.setTabOrder(self.push_square_Button, self.push_get_resolt)
        Form.setTabOrder(self.push_get_resolt, self.push_Button_0)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.push_Button_1.setText(_translate("Form", "1"))
        self.push_Button_2.setText(_translate("Form", "2"))
        self.push_Button_qw.setText(_translate("Form", ","))
        self.push_Button_8.setText(_translate("Form", "8"))
        self.push_Button_0.setText(_translate("Form", "0"))
        self.push_Button_5.setText(_translate("Form", "5"))
        self.push_Button_3.setText(_translate("Form", "3"))
        self.push_Button_7.setText(_translate("Form", "7"))
        self.push_Button_4.setText(_translate("Form", "4"))
        self.push_Button_6.setText(_translate("Form", "6"))
        self.push_Button_9.setText(_translate("Form", "9"))
        self.push_Button_neg.setText(_translate("Form", "-"))
        self.push_plus_Button.setText(_translate("Form", "+"))
        self.push_min_Button.setText(_translate("Form", "-"))
        self.push_mult_Button.setText(_translate("Form", "*"))
        self.push_div_Button.setText(_translate("Form", "/"))
        self.push_exp_Button.setText(_translate("Form", "^"))
        self.push_square_Button.setText(_translate("Form", "square"))
        self.push_get_resolt.setText(_translate("Form", "="))
